### ISSUE TITLE
Multiple reviews 1 product, 1 user

### ISSUE THREAD

**Issue by orselane** [TrustyUnitReview/ProductReview#70] opened 2024-11-24 17:09 UTC
It's possible to create duplicate reviews currently for one product by the same user. We've agreed that this was unintuitive. Modifying an existing review should be the intended behavior instead.

**Comment by Mayukh-G** [comment] 2024-11-29 21:58
Duplicate of #72

**Closed by Mayukh-G** 2024-11-29 21:58 UTC
Labels: bug, duplicate
